image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - echo 'Before script'
  # - cd reddit
  # - bundle install

build_job:
  image: docker:dind
  stage: build
  script:
    - echo 'Building'
    - docker login -u darkarren -p $docker_hub_password
    - docker build -t gitlab-reddit:latest ./reddit
    - docker tag gitlab-reddit:latest darkarren/otus-reddit:2.0
    - docker push darkarren/otus-reddit:2.0

# test_unit_job:
#   stage: test
#   services:
#     - mongo:latest
#   script:
#     - cd reddit
#     - bundle install
#     - ruby simpletest.rb

# test_integration_job:
#   stage: test
#   script:
#     - echo 'Testing 2'

# deploy_dev_job:
#   stage: review
#   script:
#     - echo 'Deploy'
#   environment:
#     name: dev
#     url: http://dev.example.com

branch review:
  image: google/cloud-sdk:latest
  stage: review
  script: 
    - gcloud --version
    - echo $gcloud_compute_service_account > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $gcloud_project_id
    - mkdir ${HOME}/.ssh
<<<<<<< HEAD
    - echo -e $ssh_key > ${HOME}/.ssh/id_rsa
    - cat ${HOME}/.ssh/id_rsa
=======
    - echo $ssh_key > ${HOME}/.ssh/id_rsa
    # - cat ${HOME}/.ssh/id_rsa
>>>>>>> create and remove vm
    - chmod 400 ${HOME}/.ssh/id_rsa
    # - ls ${HOME}/.ssh/id_rsa
    - echo -e 'Host *   \n StrictHostKeyChecking false' > ${HOME}/.ssh/config
    # - cat ${HOME}/.ssh/config
    # - gcloud compute instances list --format="table(name,networkInterfaces[].accessConfigs[0].natIP.notnull().list())" | grep gitlab-docker | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"
    - gcloud compute instances create gitlab-reddit-$CI_COMMIT_SHA --boot-disk-size=10GB --image-family reddit-docker --machine-type=g1-small --zone=europe-west3-c --restart-on-failure --tags puma-server
    - ssh -i ${HOME}/.ssh/id_rsa -l abramov $(gcloud compute instances list --format='table(name,networkInterfaces[].accessConfigs[0].natIP.notnull().list())' | grep gitlab-reddit-$CI_COMMIT_SHA | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}") "sudo docker network create reddit && sudo docker volume create reddit_db && sudo docker run -d --network=reddit --network-alias=mongo -v reddit_db:/data/db mongo:latest && sudo docker run -d --network=reddit -p 9292:9292 darkarren/otus-reddit:2.0"
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - sleep 20
    - curl $$(gcloud compute instances list --format='table(name,networkInterfaces[].accessConfigs[0].natIP.notnull().list())' | grep gitlab-reddit-$CI_COMMIT_SHA | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"):9292
    - gcloud compute instances delete gitlab-reddit-$CI_COMMIT_SHA --quiet --zone europe-west3-c
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
