dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: cI9xmxUWu0Q4pGLX4AFLYqm/OF5yA0mhHQAnGynGZUL7uFqPVvRXJ9Mc005juQOi9fG3lovUuujEhiFsZRCJDB2cl3d8AhkjZbYzIwE0i4zOfYDE1RycjbYGjggo3v21hD7YZVjfY7rWmS+hvX3BknYUZ2D2C2ZrCWOsk31uNHBReCEFQOq/7yw808xQDfqQVpsUuDljgxEjfUhLiKx1+Add/15/Wx5t2WBesH2HMoRixaq1FRmhc0WvtcJvE42I45fe2Os2JhOa/YyDUiO6EbP7s9tPsca5HF12nTtxhbdNxWDA8i1SmuSbTUI5LACGwzK0OLytr0xZMtsZTDiWPrzILbR1NRGcKFXWQn8RBiuBGgEDT6XR55t4lMLK3Hy3Ny2qpTNsPgpKOjfp/An27e8nnb5QkFW50cHNmGtsqW3r61N0zeFBEd6RfzJ/VqK5hBcDxsAtbpRV7bxtSWI/n+6oAsZ7x72CWHCTjkIfuvKCd4jDjFeUXym8d15GtZ2dWmtq3VFnM8wgQZCAkDHptp5AbaqffyL2zsI0KYYSrQtrHbffYGQF57fO8tPl25zIAIuBJbhzXMbDfpHJztQk87+phWvmYRBLVNILNFcJXoZsKNfkYoXO64LXBsxkkueBYH3+qyEBBxU5PXiE4mVJcGP31GSwRS+ba6eAOywWbIw=
