version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION} # 3.2
    ports:
      - 27017:27017
    volumes:
      - post_db:/data/db
    command:
      - '-bind_ip=0.0.0.0'
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_VERSION} # 1.0
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - target: 9292 # the port inside the container
        published: ${PUBLIC_PORT} # the publicly exposed port
        protocol: tcp # the port protocol (tcp or udp)
        mode: host # host for publishing a host port on each node, or ingress for a swarm mode port to be load balanced.
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION} # 1.0
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment

volumes:
  post_db:
  # prometheus_data:

networks:
#   reddit:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
